package gamerglance_package;

import java.io.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Team_Hmphbics
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_Panel = new javax.swing.JPanel();
        Login_Panel = new javax.swing.JPanel();
        Username_Email_TextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        Username_Email_label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Login_Text_Label = new javax.swing.JLabel();
        StayLogin_CheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        BG_Image_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        BG_Panel.setBackground(new java.awt.Color(0, 0, 0));
        BG_Panel.setPreferredSize(new java.awt.Dimension(1280, 720));
        BG_Panel.setLayout(null);

        Login_Panel.setBackground(new java.awt.Color(0, 0, 0));
        Login_Panel.setLayout(null);
        Login_Panel.add(Username_Email_TextField);
        Username_Email_TextField.setBounds(77, 160, 218, 22);
        Login_Panel.add(PasswordField);
        PasswordField.setBounds(77, 240, 218, 22);

        Username_Email_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Username_Email_label.setForeground(new java.awt.Color(255, 255, 255));
        Username_Email_label.setText("Username / Email");
        Login_Panel.add(Username_Email_label);
        Username_Email_label.setBounds(77, 132, 220, 17);

        Password_Label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Password_Label.setForeground(new java.awt.Color(255, 255, 255));
        Password_Label.setText("Password");
        Login_Panel.add(Password_Label);
        Password_Label.setBounds(77, 212, 220, 17);
        Login_Panel.add(jSeparator1);
        jSeparator1.setBounds(77, 104, 218, 10);

        Login_Text_Label.setFont(new java.awt.Font("Brush Script MT", 1, 48)); // NOI18N
        Login_Text_Label.setForeground(new java.awt.Color(255, 255, 255));
        Login_Text_Label.setText("Login");
        Login_Panel.add(Login_Text_Label);
        Login_Text_Label.setBounds(120, 38, 114, 60);

        StayLogin_CheckBox.setBackground(new java.awt.Color(255, 255, 255));
        StayLogin_CheckBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StayLogin_CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        StayLogin_CheckBox.setText("Stay Login");
        Login_Panel.add(StayLogin_CheckBox);
        StayLogin_CheckBox.setBounds(77, 280, 220, 21);

        jButton1.setText("Login");
        Login_Panel.add(jButton1);
        jButton1.setBounds(223, 306, 72, 23);

        BG_Panel.add(Login_Panel);
        Login_Panel.setBounds(460, 90, 370, 417);

        BG_Image_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginBG_Animation.gif"))); // NOI18N
        BG_Panel.add(BG_Image_Label);
        BG_Image_Label.setBounds(0, 0, 1260, 710);

        getContentPane().add(BG_Panel);
        BG_Panel.setBounds(0, 0, 1260, 710);

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Login_Panel.setBackground(new Color(0, 0, 128, 90));
        StayLogin_CheckBox.setBackground(new Color(0, 0, 128, 90));
        BG_Image_Label.setIcon(new ImageIcon(getClass().getResource("/LoginBG_Animation.gif")));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_Image_Label;
    private javax.swing.JPanel BG_Panel;
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JLabel Login_Text_Label;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JCheckBox StayLogin_CheckBox;
    private javax.swing.JTextField Username_Email_TextField;
    private javax.swing.JLabel Username_Email_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
